import './asset/css/base.scss';
import './asset/css/style.scss';
import './asset/css/index.scss';
import './asset/css/kengaku.scss';
import './asset/css/ikou.scss';
import './asset/css/contact.scss';
// import './asset/js/apps2.js';
// import './asset/js/contact_validate.js';
// import './asset/js/kengaku_validate.js';
// import './asset/js/youtube.js';
